### ISSUE TITLE
Release package on Pypi

### ISSUE THREAD

**Issue by sveetch** [what-digital/djangocms-page-remove-meta-descr#1]
I found your package from nephila/djangocms-page-meta#50 and seems a nice solution to remove the meta description field from CMS page options.

Could you release it on Pypi so we can avoid to install as a vcs git repository ?  (Apart if it's planned to integrate your hack to "nephila/djangocms-page-meta" repo).

Thanks

**Comment by yakky** [comment]
I'll happily integrate this into upstream package if @macolo is ok with it

**Comment by macolo** [comment]
Hi guys,

I am fine with that.

@sveetch https://github.com/sveetch it's probably not needed to release
it on pypi anymore in this case.

On Mon, May 30, 2016 at 11:41 PM, Iacopo Spalletti <notifications@github.com

> wrote:
> 
> I'll happily integrate this into upstream package if @macolo
> https://github.com/macolo is ok with it
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/what-digital/djangocms-page-remove-meta-descr/issues/1#issuecomment-222557659,
> or mute the thread
> https://github.com/notifications/unsubscribe/AD3nk6FW9rN-wbWI2xDdrvyBXs0EWvfnks5qG1l5gaJpZM4IqA-9
> .

## 

Mario Colombo
Partner

what. creates digital success.

what.digital
Sihlquai 131
https://www.google.ch/maps/place/Sihlquai+131,+8005+Z%C3%BCrich/@47.3848798,8.531612,17z/data=!3m1!4b1!4m2!3m1!1s0x47900a0d7d9098df:0x56a038868927d186
8005 Zürich
https://www.google.ch/maps/place/Sihlquai+131,+8005+Z%C3%BCrich/@47.3848798,8.531612,17z/data=!3m1!4b1!4m2!3m1!1s0x47900a0d7d9098df:0x56a038868927d186

+41 78 941 73 34 <+41789417334>
mario@what.digital
Linkedin Profile https://lnkd.in/dc2Hp2i

**Comment by yakky** [comment]
Ported upstream in nephila/djangocms-page-meta#52

**Comment by sveetch** [comment]
That's cool, thank you @yakky @macolo
